/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws.
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2018, 2024 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
* File Name        : Pin.c
* Version          : 1.0.0.0
* Device(s)        : R7F702300B
* Description      : This file implements SMC pin code generation.
***********************************************************************************************************************/
/***********************************************************************************************************************
Pragma directive
***********************************************************************************************************************/
/* Start user code for pragma. Do not edit comment generated here */
/* End user code. Do not edit comment generated here */

/***********************************************************************************************************************
Includes
***********************************************************************************************************************/
#include "r_cg_macrodriver.h"
#include "r_cg_userdefine.h"
/* Start user code for include. Do not edit comment generated here */
/* End user code. Do not edit comment generated here */

/***********************************************************************************************************************
Global variables and functions
***********************************************************************************************************************/
/* Start user code for global. Do not edit comment generated here */
void R_Pins_Create_UserInit(void)
{
    /*Ethernet MDIO init*/
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(16U);
    PORT0.PCR20_3.BIT.PIPC=1;
    PORT0.PCR20_3.BIT.PM=0;
    PORT0.PWE = 0;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Initialization of the MMCA0 Card Detect Switch CD_SW1 (P24_10) pin. */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(20U);
    PORT0.PMC24.BIT.PMC24_10 |= 0x0;
    PORT0.PM24.BIT.PM24_10 |= 0x1;
    PORT0.PIBC24.BIT.PIBC24_10 |= 0x1;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;
}
/* End user code. Do not edit comment generated here */

/***********************************************************************************************************************
* Function Name: R_Pins_Create
* Description  : This function initializes Smart Configurator pins
* Arguments    : None
* Return Value : None
***********************************************************************************************************************/
void R_Pins_Create(void)
{
    /* Set ADCJ1CNV4(P21_7) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(17U);
    PORT0.PCR21_7.UINT32 = (PORT0.PCR21_7.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR21_7.UINT32 |= _PCR_ALT_OUT5;
    PORT0.PCR21_7.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR21_7.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR21_7.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ADCJ1I0(AP2_0) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(23U);
    PORT0.APCR2_0.UINT32 = _PCR_ANALOG_INPUT;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ADCJ1I1(AP2_1) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(23U);
    PORT0.APCR2_1.UINT32 = _PCR_ANALOG_INPUT;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ADCJ1I2(AP2_2) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(23U);
    PORT0.APCR2_2.UINT32 = _PCR_ANALOG_INPUT;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ADCJ2CNV0(P4_11) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(5U);
    PORT0.PCR4_11.UINT32 = (PORT0.PCR4_11.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR4_11.UINT32 |= _PCR_ALT_OUT5;
    PORT0.PCR4_11.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR4_11.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR4_11.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ADCJ2I0(AP4_0) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(25U);
    PORT0.APCR4_0.UINT32 = _PCR_ANALOG_INPUT;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set CAN0RX(P4_0) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(5U);
    PORT0.PCR4_0.UINT32 = (PORT0.PCR4_0.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR4_0.UINT32 |= _PCR_ALT_IN7;
    PORT0.PCR4_0.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set CAN0TX(P4_1) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(5U);
    PORT0.PCR4_1.UINT32 = (PORT0.PCR4_1.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR4_1.UINT32 |= _PCR_ALT_OUT3;
    PORT0.PCR4_1.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR4_1.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR4_1.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set CAN1RX(P6_7) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(7U);
    PORT0.PCR6_7.UINT32 = (PORT0.PCR6_7.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR6_7.UINT32 |= _PCR_ALT_IN7;
    PORT0.PCR6_7.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set CAN1TX(P6_8) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(7U);
    PORT0.PCR6_8.UINT32 = (PORT0.PCR6_8.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR6_8.UINT32 |= _PCR_ALT_OUT2;
    PORT0.PCR6_8.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR6_8.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR6_8.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set DPIN12(P6_12) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(7U);
    PORT0.PCR6_12.UINT32 = (PORT0.PCR6_12.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR6_12.UINT32 |= _PCR_ALT_IN4;
    PORT0.PCR6_12.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ENCA0E0(P3_2) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(4U);
    PORT0.PCR3_2.UINT32 = (PORT0.PCR3_2.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR3_2.UINT32 |= _PCR_ALT_IN5;
    PORT0.PCR3_2.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ENCA0E1(P3_3) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(4U);
    PORT0.PCR3_3.UINT32 = (PORT0.PCR3_3.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR3_3.UINT32 |= _PCR_ALT_IN5;
    PORT0.PCR3_3.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0CRS_DV(P20_7) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(16U);
    PORT0.PCR20_7.UINT32 = (PORT0.PCR20_7.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR20_7.UINT32 |= _PCR_ALT_IN2;
    PORT0.PCR20_7.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0LINKSTA(P20_1) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(16U);
    PORT0.PCR20_1.UINT32 = (PORT0.PCR20_1.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR20_1.UINT32 |= _PCR_ALT_IN2;
    PORT0.PCR20_1.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0MDC(P20_6) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(16U);
    PORT0.PCR20_6.UINT32 = (PORT0.PCR20_6.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR20_6.UINT32 |= _PCR_ALT_OUT2;
    PORT0.PCR20_6.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR20_6.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR20_6.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0MDIO(P20_3) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(16U);
    PORT0.PCR20_3.UINT32 = (PORT0.PCR20_3.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR20_3.UINT32 |= _PCR_ALT_IN2;
    PORT0.PCR20_3.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0RXCLK(P10_2) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(10U);
    PORT0.PCR10_2.UINT32 = (PORT0.PCR10_2.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR10_2.UINT32 |= _PCR_ALT_IN2;
    PORT0.PCR10_2.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0RXD0(P10_3) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(10U);
    PORT0.PCR10_3.UINT32 = (PORT0.PCR10_3.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR10_3.UINT32 |= _PCR_ALT_IN2;
    PORT0.PCR10_3.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0RXD1(P10_4) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(10U);
    PORT0.PCR10_4.UINT32 = (PORT0.PCR10_4.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR10_4.UINT32 |= _PCR_ALT_IN2;
    PORT0.PCR10_4.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0RXD2(P10_5) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(10U);
    PORT0.PCR10_5.UINT32 = (PORT0.PCR10_5.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR10_5.UINT32 |= _PCR_ALT_IN2;
    PORT0.PCR10_5.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0RXD3(P10_6) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(10U);
    PORT0.PCR10_6.UINT32 = (PORT0.PCR10_6.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR10_6.UINT32 |= _PCR_ALT_IN2;
    PORT0.PCR10_6.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0RXDV(P10_7) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(10U);
    PORT0.PCR10_7.UINT32 = (PORT0.PCR10_7.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR10_7.UINT32 |= _PCR_ALT_IN2;
    PORT0.PCR10_7.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0RXER(P10_0) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(10U);
    PORT0.PCR10_0.UINT32 = (PORT0.PCR10_0.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR10_0.UINT32 |= _PCR_ALT_IN2;
    PORT0.PCR10_0.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0TXCLK(P10_1) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(10U);
    PORT0.PCR10_1.UINT32 = (PORT0.PCR10_1.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR10_1.UINT32 |= _PCR_ALT_IN2;
    PORT0.PCR10_1.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0TXD0(P20_9) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(16U);
    PORT0.PCR20_9.UINT32 = (PORT0.PCR20_9.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR20_9.UINT32 |= _PCR_ALT_OUT2;
    PORT0.PCR20_9.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR20_9.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR20_9.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0TXD1(P20_10) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(16U);
    PORT0.PCR20_10.UINT32 = (PORT0.PCR20_10.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR20_10.UINT32 |= _PCR_ALT_OUT2;
    PORT0.PCR20_10.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR20_10.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR20_10.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0TXD2(P20_12) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(16U);
    PORT0.PCR20_12.UINT32 = (PORT0.PCR20_12.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR20_12.UINT32 |= _PCR_ALT_OUT2;
    PORT0.PCR20_12.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR20_12.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR20_12.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0TXD3(P20_13) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(16U);
    PORT0.PCR20_13.UINT32 = (PORT0.PCR20_13.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR20_13.UINT32 |= _PCR_ALT_OUT2;
    PORT0.PCR20_13.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR20_13.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR20_13.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0TXEN(P20_14) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(16U);
    PORT0.PCR20_14.UINT32 = (PORT0.PCR20_14.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR20_14.UINT32 |= _PCR_ALT_OUT2;
    PORT0.PCR20_14.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR20_14.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR20_14.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set ETNB0TXER(P20_8) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(16U);
    PORT0.PCR20_8.UINT32 = (PORT0.PCR20_8.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR20_8.UINT32 |= _PCR_ALT_OUT2;
    PORT0.PCR20_8.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR20_8.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR20_8.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set INTP4(P2_0) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(3U);
    PORT0.PCR2_0.UINT32 = (PORT0.PCR2_0.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR2_0.UINT32 |= _PCR_ALT_IN4;
    PORT0.PCR2_0.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set INTP5(P2_7) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(3U);
    PORT0.PCR2_7.UINT32 = (PORT0.PCR2_7.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR2_7.UINT32 |= _PCR_ALT_IN2;
    PORT0.PCR2_7.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set INTP21(P2_3) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(3U);
    PORT0.PCR2_3.UINT32 = (PORT0.PCR2_3.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR2_3.UINT32 |= _PCR_ALT_IN4;
    PORT0.PCR2_3.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set MMCA0CLK(P24_4) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(20U);
    PORT0.PCR24_4.UINT32 = (PORT0.PCR24_4.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR24_4.UINT32 |= _PCR_ALT_OUT7;
    PORT0.PCR24_4.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR24_4.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR24_4.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set MMCA0CMD(P24_5) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(20U);
    PORT0.PCR24_5.UINT32 = (PORT0.PCR24_5.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR24_5.UINT32 |= _PCR_DIRECT_ALT_MODE7;
    PORT0.PCR24_5.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR24_5.UINT32 &= _PCR_DIRECT_ALT_MODE_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set MMCA0DAT0(P24_6) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(20U);
    PORT0.PCR24_6.UINT32 = (PORT0.PCR24_6.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR24_6.UINT32 |= _PCR_DIRECT_ALT_MODE7;
    PORT0.PCR24_6.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR24_6.UINT32 &= _PCR_DIRECT_ALT_MODE_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set MMCA0DAT1(P24_7) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(20U);
    PORT0.PCR24_7.UINT32 = (PORT0.PCR24_7.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR24_7.UINT32 |= _PCR_DIRECT_ALT_MODE7;
    PORT0.PCR24_7.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR24_7.UINT32 &= _PCR_DIRECT_ALT_MODE_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set MMCA0DAT2(P24_8) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(20U);
    PORT0.PCR24_8.UINT32 = (PORT0.PCR24_8.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR24_8.UINT32 |= _PCR_DIRECT_ALT_MODE7;
    PORT0.PCR24_8.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR24_8.UINT32 &= _PCR_DIRECT_ALT_MODE_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set MMCA0DAT3(P24_9) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(20U);
    PORT0.PCR24_9.UINT32 = (PORT0.PCR24_9.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR24_9.UINT32 |= _PCR_DIRECT_ALT_MODE7;
    PORT0.PCR24_9.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR24_9.UINT32 &= _PCR_DIRECT_ALT_MODE_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set MSPI3SC(P22_4) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(18U);
    PORT0.PCR22_4.UINT32 = (PORT0.PCR22_4.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR22_4.UINT32 |= _PCR_ALT_IN4;
    PORT0.PCR22_4.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set MSPI3SI(P22_1) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(18U);
    PORT0.PCR22_1.UINT32 = (PORT0.PCR22_1.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR22_1.UINT32 |= _PCR_ALT_IN4;
    PORT0.PCR22_1.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set MSPI3SO(P22_0) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(18U);
    PORT0.PCR22_0.UINT32 = (PORT0.PCR22_0.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR22_0.UINT32 |= _PCR_DIRECT_ALT_MODE4;
    PORT0.PCR22_0.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR22_0.UINT32 &= _PCR_DIRECT_ALT_MODE_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set PWGC66O(P10_11) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(10U);
    PORT0.PCR10_11.UINT32 = (PORT0.PCR10_11.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR10_11.UINT32 |= _PCR_ALT_OUT8;
    PORT0.PCR10_11.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR10_11.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR10_11.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set PWGC67O(P10_12) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(10U);
    PORT0.PCR10_12.UINT32 = (PORT0.PCR10_12.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR10_12.UINT32 |= _PCR_ALT_OUT8;
    PORT0.PCR10_12.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR10_12.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR10_12.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set PWGC68O(P10_13) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(10U);
    PORT0.PCR10_13.UINT32 = (PORT0.PCR10_13.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR10_13.UINT32 |= _PCR_ALT_OUT8;
    PORT0.PCR10_13.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR10_13.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR10_13.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set RIIC0SCL(P17_3) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(13U);
    PORT0.PCR17_3.UINT32 = (PORT0.PCR17_3.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR17_3.UINT32 |= _PCR_ALT_IN4;
    PORT0.PCR17_3.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set RIIC0SDA(P17_2) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(13U);
    PORT0.PCR17_2.UINT32 = (PORT0.PCR17_2.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR17_2.UINT32 |= _PCR_ALT_IN4;
    PORT0.PCR17_2.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set RLIN31RX(P2_4) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(3U);
    PORT0.PCR2_4.UINT32 = (PORT0.PCR2_4.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR2_4.UINT32 |= _PCR_ALT_IN7;
    PORT0.PCR2_4.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set RLIN31TX(P2_5) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(3U);
    PORT0.PCR2_5.UINT32 = (PORT0.PCR2_5.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR2_5.UINT32 |= _PCR_ALT_OUT3;
    PORT0.PCR2_5.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR2_5.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR2_5.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set RLIN39RX(P6_2) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(7U);
    PORT0.PCR6_2.UINT32 = (PORT0.PCR6_2.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR6_2.UINT32 |= _PCR_ALT_IN7;
    PORT0.PCR6_2.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set RLIN39TX(P6_3) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(7U);
    PORT0.PCR6_3.UINT32 = (PORT0.PCR6_3.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR6_3.UINT32 |= _PCR_ALT_OUT4;
    PORT0.PCR6_3.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR6_3.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR6_3.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set RSENT1RX(P3_5) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(4U);
    PORT0.PCR3_5.UINT32 = (PORT0.PCR3_5.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR3_5.UINT32 |= _PCR_ALT_IN3;
    PORT0.PCR3_5.UINT32 |= _PCR_SET_PMC;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set RSENT1SPCO(P17_4) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(13U);
    PORT0.PCR17_4.UINT32 = (PORT0.PCR17_4.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR17_4.UINT32 |= _PCR_ALT_OUT3;
    PORT0.PCR17_4.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR17_4.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR17_4.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set TAUD0O1(P2_1) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(3U);
    PORT0.PCR2_1.UINT32 = (PORT0.PCR2_1.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR2_1.UINT32 |= _PCR_ALT_OUT6;
    PORT0.PCR2_1.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR2_1.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR2_1.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set TAUD0O2(P2_2) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(3U);
    PORT0.PCR2_2.UINT32 = (PORT0.PCR2_2.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR2_2.UINT32 |= _PCR_ALT_OUT6;
    PORT0.PCR2_2.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR2_2.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR2_2.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set TAUD2O13(P6_5) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(7U);
    PORT0.PCR6_5.UINT32 = (PORT0.PCR6_5.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR6_5.UINT32 |= _PCR_ALT_OUT6;
    PORT0.PCR6_5.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR6_5.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR6_5.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

    /* Set TAUD2O14(P6_6) pin */
    PORT0.PKCPROT = _WRITE_PROTECT_ENABLE;
    PORT0.PWE = SETBIT(7U);
    PORT0.PCR6_6.UINT32 = (PORT0.PCR6_6.UINT32 & _PCR_DEFAULT_VALUE) | _PCR_SET_PM;
    PORT0.PCR6_6.UINT32 |= _PCR_ALT_OUT6;
    PORT0.PCR6_6.UINT32 |= _PCR_SET_PMC;
    PORT0.PCR6_6.UINT32 &= _PCR_CLEAR_PM;
    PORT0.PCR6_6.UINT32 &= _PCR_ALT_OUT_SETTING;
    PORT0.PWE = _PORT_WRITE_PROTECT_DISABLE;
    PORT0.PKCPROT = _WRITE_PROTECT_DISABLE;

}
